packages:
  - './packages/api-generator'
  - './packages/backend'
  - './packages/cutiekey.js'
  - './packages/frontend'
  - './packages/megalodon'
  - './packages/misskey-bubble-game'
  - './packages/misskey-js'
  - './packages/misskey-reversi'
  - './packages/sw'
