version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    networks:
      - external_network
      - internal_network
    volumes:
      - ../:/workspace:cached

  db:
    environment:
      POSTGRES_DB: cutiekey
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: 5s
      retries: 20
      test: 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER'
    image: postgres:16-alpine
    networks:
      - internal_network
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    healthcheck:
      interval: 5s
      retries: 20
      test: 'redis-cli ping'
    image: redis:7-alpine
    networks:
      - internal_network
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

networks:
  internal_network:
    internal: true
  external_network:
